package retrofit.bwei.com.zhoukaoyisunday.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import retrofit.bwei.com.zhoukaoyisunday.bean.DataBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DATA_BEAN".
*/
public class DataBeanDao extends AbstractDao<DataBean, Long> {

    public static final String TABLENAME = "DATA_BEAN";

    /**
     * Properties of entity DataBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property BargainPrice = new Property(1, double.class, "bargainPrice", false, "BARGAIN_PRICE");
        public final static Property Createtime = new Property(2, String.class, "createtime", false, "CREATETIME");
        public final static Property DetailUrl = new Property(3, String.class, "detailUrl", false, "DETAIL_URL");
        public final static Property Images = new Property(4, String.class, "images", false, "IMAGES");
        public final static Property Itemtype = new Property(5, int.class, "itemtype", false, "ITEMTYPE");
        public final static Property Pid = new Property(6, int.class, "pid", false, "PID");
        public final static Property Price = new Property(7, double.class, "price", false, "PRICE");
        public final static Property Pscid = new Property(8, int.class, "pscid", false, "PSCID");
        public final static Property Salenum = new Property(9, int.class, "salenum", false, "SALENUM");
        public final static Property Sellerid = new Property(10, int.class, "sellerid", false, "SELLERID");
        public final static Property Subhead = new Property(11, String.class, "subhead", false, "SUBHEAD");
        public final static Property Title = new Property(12, String.class, "title", false, "TITLE");
    }


    public DataBeanDao(DaoConfig config) {
        super(config);
    }
    
    public DataBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DATA_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"BARGAIN_PRICE\" REAL NOT NULL ," + // 1: bargainPrice
                "\"CREATETIME\" TEXT," + // 2: createtime
                "\"DETAIL_URL\" TEXT," + // 3: detailUrl
                "\"IMAGES\" TEXT," + // 4: images
                "\"ITEMTYPE\" INTEGER NOT NULL ," + // 5: itemtype
                "\"PID\" INTEGER NOT NULL ," + // 6: pid
                "\"PRICE\" REAL NOT NULL ," + // 7: price
                "\"PSCID\" INTEGER NOT NULL ," + // 8: pscid
                "\"SALENUM\" INTEGER NOT NULL ," + // 9: salenum
                "\"SELLERID\" INTEGER NOT NULL ," + // 10: sellerid
                "\"SUBHEAD\" TEXT," + // 11: subhead
                "\"TITLE\" TEXT);"); // 12: title
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DATA_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DataBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindDouble(2, entity.getBargainPrice());
 
        String createtime = entity.getCreatetime();
        if (createtime != null) {
            stmt.bindString(3, createtime);
        }
 
        String detailUrl = entity.getDetailUrl();
        if (detailUrl != null) {
            stmt.bindString(4, detailUrl);
        }
 
        String images = entity.getImages();
        if (images != null) {
            stmt.bindString(5, images);
        }
        stmt.bindLong(6, entity.getItemtype());
        stmt.bindLong(7, entity.getPid());
        stmt.bindDouble(8, entity.getPrice());
        stmt.bindLong(9, entity.getPscid());
        stmt.bindLong(10, entity.getSalenum());
        stmt.bindLong(11, entity.getSellerid());
 
        String subhead = entity.getSubhead();
        if (subhead != null) {
            stmt.bindString(12, subhead);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(13, title);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DataBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindDouble(2, entity.getBargainPrice());
 
        String createtime = entity.getCreatetime();
        if (createtime != null) {
            stmt.bindString(3, createtime);
        }
 
        String detailUrl = entity.getDetailUrl();
        if (detailUrl != null) {
            stmt.bindString(4, detailUrl);
        }
 
        String images = entity.getImages();
        if (images != null) {
            stmt.bindString(5, images);
        }
        stmt.bindLong(6, entity.getItemtype());
        stmt.bindLong(7, entity.getPid());
        stmt.bindDouble(8, entity.getPrice());
        stmt.bindLong(9, entity.getPscid());
        stmt.bindLong(10, entity.getSalenum());
        stmt.bindLong(11, entity.getSellerid());
 
        String subhead = entity.getSubhead();
        if (subhead != null) {
            stmt.bindString(12, subhead);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(13, title);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DataBean readEntity(Cursor cursor, int offset) {
        DataBean entity = new DataBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getDouble(offset + 1), // bargainPrice
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // createtime
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // detailUrl
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // images
            cursor.getInt(offset + 5), // itemtype
            cursor.getInt(offset + 6), // pid
            cursor.getDouble(offset + 7), // price
            cursor.getInt(offset + 8), // pscid
            cursor.getInt(offset + 9), // salenum
            cursor.getInt(offset + 10), // sellerid
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // subhead
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12) // title
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DataBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBargainPrice(cursor.getDouble(offset + 1));
        entity.setCreatetime(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDetailUrl(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setImages(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setItemtype(cursor.getInt(offset + 5));
        entity.setPid(cursor.getInt(offset + 6));
        entity.setPrice(cursor.getDouble(offset + 7));
        entity.setPscid(cursor.getInt(offset + 8));
        entity.setSalenum(cursor.getInt(offset + 9));
        entity.setSellerid(cursor.getInt(offset + 10));
        entity.setSubhead(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setTitle(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DataBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DataBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DataBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
